import turtle

def draw_smiley(x, y):
    t = turtle.Turtle()
    t.hideturtle()
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    # Gözler (beyaz + siyah)
    for ex in [-20, 20]:
        t.penup()
        t.goto(x + ex, y + 60)
        t.pendown()
        t.fillcolor("white")
        t.begin_fill()
        t.circle(10)
        t.end_fill()
        t.penup()
        t.goto(x + ex, y + 65)
        t.pendown()
        t.fillcolor("black")
        t.begin_fill()
        t.circle(4)
        t.end_fill()
    # Ağız (kırmızı yay)
    t.penup()
    t.goto(x - 25, y + 30)
    t.setheading(-60)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    t.circle(30, 120)
    # Yayın altını düz çizgiyle kapat
    pos = t.pos()
    t.goto(x + 25, y + 30)
    t.goto(x - 25, y + 30)
    t.end_fill()


def draw_cool(x, y):
    t = turtle.Turtle()
    t.hideturtle()
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    # Gözlükler
    t.penup()
    t.goto(x - 20, y + 50)
    t.pendown()
    t.fillcolor("black")
    t.begin_fill()
    t.circle(15)
    t.end_fill()
    t.penup()
    t.goto(x + 20, y + 50)
    t.pendown()
    t.begin_fill()
    t.circle(15)
    t.end_fill()
    # Gözlük köprüsü
    t.penup()
    t.goto(x - 10, y + 70)
    t.pendown()
    t.width(4)
    t.goto(x + 10, y + 70)
    t.width(1)
    # Ağız
    t.penup()
    t.goto(x - 25, y + 35)
    t.setheading(-60)
    t.pendown()
    t.width(4)
    t.circle(30, 120)
    t.width(1)

def draw_surprised(x, y):
    t = turtle.Turtle()
    t.hideturtle()
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    # Büyük gözler
    t.penup()
    t.goto(x - 20, y + 65)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    t.circle(11)
    t.end_fill()
    t.penup()
    t.goto(x + 20, y + 65)
    t.pendown()
    t.begin_fill()
    t.circle(11)
    t.end_fill()
    # Göz bebekleri
    t.penup()
    t.goto(x - 20, y + 68)
    t.pendown()
    t.fillcolor("black")
    t.begin_fill()
    t.circle(5)
    t.end_fill()
    t.penup()
    t.goto(x + 20, y + 68)
    t.pendown()
    t.begin_fill()
    t.circle(5)
    t.end_fill()
    # Ağız (büyük O)
    t.penup()
    t.goto(x, y + 25)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    t.circle(13)
    t.end_fill()
   

def draw_laughing(x, y):
    t = turtle.Turtle()
    t.hideturtle()
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.fillcolor("yellow")
    t.begin_fill()
    t.circle(50)
    t.end_fill()
    # Kapalı gözler
    t.penup()
    t.goto(x-12 , y + 60)
    t.setheading(120)
    t.pendown()
    t.width(3)
    t.circle(10, 120)
    t.width(1)
    t.penup()
    t.goto(x + 30, y + 60)
    t.setheading(120)
    t.pendown()
    t.width(3)
    t.circle(10, 120)
    t.width(1)
    # Büyük gülüş (kırmızı yay ve dişler)
    t.penup()
    t.goto(x - 25, y + 35)
    t.setheading(-60)
    t.pendown()
    t.fillcolor("red")
    t.begin_fill()
    t.circle(30, 120)
    # Yayın altını düz çizgiyle kapat
    t.goto(x + 25, y + 35)
    t.goto(x - 25, y + 35)
    t.end_fill()
    # Gözyaşları
    t.penup()
    t.goto(x - 30, y + 50)
    t.pendown()
    t.fillcolor("cyan")
    t.begin_fill()
    t.circle(7)
    t.end_fill()
    t.penup()
    t.goto(x + 43, y + 50)
    t.pendown()
    t.begin_fill()
    t.circle(7)
    t.end_fill()